use_frameworks!

target 'PDColorPicker_Example' do
  pod 'PDColorPicker', :path => '../'

  target 'PDColorPicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
