use_frameworks!

project 'PDColorPickerExample.xcodeproj'

platform :ios, '9.0'

target 'PDColorPicker_Example' do
  pod 'PDColorPicker', :path => '../'

  target 'PDColorPicker_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble', :inhibit_warnings => true
  end
end
